# Generated by Django 6.0.2 on 2026-02-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SumpReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("water_level", models.IntegerField()),
                ("mud_level", models.IntegerField()),
                ("leakage_current", models.IntegerField()),
                ("motor_status", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
